### ISSUE TITLE
Support alphanumeric entries 

### ISSUE THREAD

**Issue by iamevansobeng** [guilhermerodz/input-otp#54] opened 2024-06-19 09:54 UTC
**Is your feature request related to a problem? Please describe.**
On desktop, it works when a regex pattern for alphanumeric is added as a prop but doesn't work for mobile. A client pointed it out and it took me way too long to find it since I was debugging on my laptop and not on an actual  mobile device

**Describe the solution you'd like**
A simple prop for the type of input, preferably an enum "numeric" | "alphanumeric" | "alpha"

**Describe alternatives you've considered**
I had a workaround to fix the issue however I noticed you have pending pull requests so I didn't bother creating another.

**Comment by guilhermerodz** [comment] 2024-07-11 05:10
hey @iamevansobeng is that a duplicate of #56? If so, please check the reply I wrote there

**Comment by guilhermerodz** [comment] 2024-08-09 23:22
Duplicate of #56 (most likely)

**Comment by guilhermerodz** [comment] 2024-08-09 23:22
Duplicate of https://github.com/guilhermerodz/input-otp/issues/56 (most likely)

**Closed by guilhermerodz** 2024-08-09 23:22 UTC
