### ISSUE TITLE
input-otp isn't keyboard accessible when used with radix/dialog

### ISSUE THREAD

**Issue by AayushKarki714** [guilhermerodz/input-otp#59] opened 2024-07-18 04:57 UTC
Thanks for such an awesome library. I am facing an issue. Why doesn't it work as expected when used within dialog. When input-otp is focused and then I press tab to focus the next interactive element. It skips over the interactive element below it and focuses on the DialogContent.

Here is short demo: 

https://github.com/user-attachments/assets/4787751b-f192-438a-87c3-ce7d3cd71877

**Comment by AayushKarki714** [comment] 2024-07-25 12:56
@guilhermerodz can you please help me with this.

**Comment by guilhermerodz** [comment] 2024-08-03 19:43
@AayushKarki714 I don't get exactly what this means. The `input-otp` is a single HTML input, which means pressing tab twice will focus 1. on your OTP input (not per each slot but for the whole input), then will focus 2. on your dialog.

Is that behavior any different when outside of a dialog?

**Comment by guilhermerodz** [comment] 2024-08-09 23:35
Closing this issue temporarily while I can't reproduce it locally. Can you provide a CodeSandbox or something like that?

**Closed by guilhermerodz** 2024-08-09 23:35 UTC
Labels: bug

**Comment by s-richards** [comment] 2025-03-26 02:07
My team was facing the same issue. It turned out to be the conditional rendering of the fake caret. Showing/hiding it using css, i.e. `<div className={clsx('absolute pointer-events-none inset-0 items-center justify-center animate-caret-blink', hasFakeCaret ? 'flex' : 'hidden'}>`, instead of conditionally rendering it fixed the issue. Using a pseudo element with the Slot also works.
